baseUrl= "http://example.com/"
LanguageCode= "en-EN"
theme = "casper"
Title= "AshTop5Tech"
paginate = 3
DisqusShortname = "YOUR_SHORT_NAME_HERE"
Copyright = "All rights reserved - 2016"
canonifyurls = true


[params]
  description = "Tech stuff you need to know"
  cover = "images/cover.jpg"
  author = "Ash Yadav"
  authorlocation = "NewYork, USA"
  authorwebsite = "http://ash.zzzz.io."
  bio= "my bio"
  # logo = "images/logo.png"
  googleAnalyticsUserID = "XX-79101-12"
  # Optional RSS-Link, if not provided it defaults to the standard index.xml
  #RSSLink = "http://feeds.feedburner.com/..." 
  #githubName = "ashyadav"
  twitterName = "ashyadav"
  facebookName = "ashyadav"
  # linkedinName = ""
  # set true if you are not proud of using Hugo (true will hide the footer note "Proudly published with HUGO.....")
  hideHUGOSupport = false

[[menu.main]]
  name = "Blog"
  weight = -120
  identifier = "blog"
  url = "/"

[[menu.main]]
  name = "About me"
  weight = -110
  identifier = "about"
  url = "/about"

